apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-publisher
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "checkout"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
        dapr.io/side-volume-mounts: "iotedge-spiffe-agent-socket=/run/iotedge/sockets/"
        dapr.io/side-volume-mounts-read-write: "true"
    spec:
      containers:
      - name: publisher
        image: dmqttdemo.azurecr.io/dapr/pubsubexample_pub:latest
      volumes:
      - name: iotedge-spiffe-agent-socket
        hostPath:
          path: /run/iotedge/sockets/
          type: DirectoryOrCreate
