apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderpubsub
  namespace: default
spec:
  type: pubsub.mqtte4k
  version: v1
  metadata:
  - name: url
    value: "tcp://admin:public@mqttbroker:1883"
  - name: qos
    value: 1
  - name: retain
    value: "false"
  - name: cleanSession
    value: "true"
  - name: backOffMaxRetries
    value: "0"
scopes:
  - orderprocessing
  - checkout
