apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-subscriber
  labels:
    app: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: busybox:latest
        command: ["sleep"]
        args: ["10000000"]
        volumeMounts:
          - name: iotedge-spiffe-agent-socket
            mountPath: /run/iotedge/sockets/
      volumes:
      - name: iotedge-spiffe-agent-socket
        hostPath:
          path: /run/iotedge/sockets/
          type: DirectoryOrCreate
