apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-publisher
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "checkout"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: publisher
        image: dmqttdemo.azurecr.io/dapr/pubsubexample_pub:latest
        volumeMounts:
          - name: iotedge-spiffe-agent-socket
            mountPath: /run/iotedge/sockets/
      initContainers:
      - name: set-ownership
        image: busybox:latest
        command: ["sh", "-c", "chmod 666 /run/iotedge/sockets/workloadapi.sock"]
        volumeMounts:
          - name: iotedge-spiffe-agent-socket
            mountPath: /run/iotedge/sockets/
      volumes:
      - name: iotedge-spiffe-agent-socket
        hostPath:
          path: /run/iotedge/sockets/
          type: DirectoryOrCreate
