apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-publisher
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "checkout"
        dapr.io/app-protocol: "http"
    spec:
      containers:
      - name: publisher
        image: dmqttdemo.azurecr.io/dapr/pubsubexample_pub:latest